// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: controlplane.proto

// The proxy <-> control-plane wire protocol (docs/datasource-registration.md).
// Single source of truth for both sides' generated bindings. Internal, trusted
// service-to-service surface only — the web UI keeps talking HTTP/JSON to control-plane.

package proxymonsterv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_Register_FullMethodName           = "/proxymonster.v1.ControlPlane/Register"
	ControlPlane_PushCatalog_FullMethodName        = "/proxymonster.v1.ControlPlane/PushCatalog"
	ControlPlane_ValidateToken_FullMethodName      = "/proxymonster.v1.ControlPlane/ValidateToken"
	ControlPlane_Decide_FullMethodName             = "/proxymonster.v1.ControlPlane/Decide"
	ControlPlane_PushSchemaFragment_FullMethodName = "/proxymonster.v1.ControlPlane/PushSchemaFragment"
	ControlPlane_CloseConnection_FullMethodName    = "/proxymonster.v1.ControlPlane/CloseConnection"
	ControlPlane_Events_FullMethodName             = "/proxymonster.v1.ControlPlane/Events"
	ControlPlane_RunExec_FullMethodName            = "/proxymonster.v1.ControlPlane/RunExec"
	ControlPlane_TableDetailExec_FullMethodName    = "/proxymonster.v1.ControlPlane/TableDetailExec"
	ControlPlane_ReportCompletion_FullMethodName   = "/proxymonster.v1.ControlPlane/ReportCompletion"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneClient interface {
	// A proxy declares its identity on boot. Idempotent, upsert by name.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// The proxy pushes the catalog it introspected itself.
	PushCatalog(ctx context.Context, in *CatalogRequest, opts ...grpc.CallOption) (*CatalogResponse, error)
	// Wire-protocol auth handshake — once per session. "May this session open?"
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*WireIdentity, error)
	// Per-query enforcement decision. Takes the RAW token, re-validated +
	// re-resolved server-side every call — never a client-cached principal.
	Decide(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*WireDecision, error)
	// Per-connection schema fragment push on the enforcement channel.
	PushSchemaFragment(ctx context.Context, in *SchemaFragmentPush, opts ...grpc.CallOption) (*SchemaFragmentAck, error)
	// Proxy-initiated connection close; the control-plane idle-sweep is the backstop.
	CloseConnection(ctx context.Context, in *CloseConnectionRequest, opts ...grpc.CallOption) (*CloseConnectionResponse, error)
	// Proxy-initiated stream: liveness (stream open == alive) + refresh push.
	Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlEvent], error)
	// The CP-driven execution channel. PROXY-DIALED bidi: the control-plane nudges the proxy over Events
	// (OpenRunChannel) to open this, so data flows both ways without the control-plane ever dialing into the
	// proxy. It serves web-editor and workflow execution through the same backend + Decide path, streaming
	// the decision and masked rows back.
	RunExec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyRunMsg, ControlRunMsg], error)
	// On-demand admin table-browser introspection. Also PROXY-DIALED: request selectors ride the Events
	// nudge and the rich shared TableDetail response returns as JSON on this short-lived channel.
	TableDetailExec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyTableDetailMsg, ControlTableDetailMsg], error)
	// Post-execution result-volume report the proxy sends after it finishes relaying one statement's result
	// to the client. Audit-only: it records a completion event chained onto the decision's audit row (never
	// a re-decision), giving the audit monitor the rows/bytes signal the pre-execution decision could not
	// carry. Best-effort — the proxy fires it off the client session's critical path and a failure never
	// affects the query. A DENY relays nothing, so it produces no completion.
	ReportCompletion(ctx context.Context, in *CompletionReport, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) PushCatalog(ctx context.Context, in *CatalogRequest, opts ...grpc.CallOption) (*CatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatalogResponse)
	err := c.cc.Invoke(ctx, ControlPlane_PushCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*WireIdentity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireIdentity)
	err := c.cc.Invoke(ctx, ControlPlane_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Decide(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*WireDecision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireDecision)
	err := c.cc.Invoke(ctx, ControlPlane_Decide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) PushSchemaFragment(ctx context.Context, in *SchemaFragmentPush, opts ...grpc.CallOption) (*SchemaFragmentAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemaFragmentAck)
	err := c.cc.Invoke(ctx, ControlPlane_PushSchemaFragment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) CloseConnection(ctx context.Context, in *CloseConnectionRequest, opts ...grpc.CallOption) (*CloseConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseConnectionResponse)
	err := c.cc.Invoke(ctx, ControlPlane_CloseConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[0], ControlPlane_Events_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventsRequest, ControlEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_EventsClient = grpc.ServerStreamingClient[ControlEvent]

func (c *controlPlaneClient) RunExec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyRunMsg, ControlRunMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[1], ControlPlane_RunExec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProxyRunMsg, ControlRunMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_RunExecClient = grpc.BidiStreamingClient[ProxyRunMsg, ControlRunMsg]

func (c *controlPlaneClient) TableDetailExec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyTableDetailMsg, ControlTableDetailMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[2], ControlPlane_TableDetailExec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProxyTableDetailMsg, ControlTableDetailMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_TableDetailExecClient = grpc.BidiStreamingClient[ProxyTableDetailMsg, ControlTableDetailMsg]

func (c *controlPlaneClient) ReportCompletion(ctx context.Context, in *CompletionReport, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ControlPlane_ReportCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
type ControlPlaneServer interface {
	// A proxy declares its identity on boot. Idempotent, upsert by name.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// The proxy pushes the catalog it introspected itself.
	PushCatalog(context.Context, *CatalogRequest) (*CatalogResponse, error)
	// Wire-protocol auth handshake — once per session. "May this session open?"
	ValidateToken(context.Context, *ValidateTokenRequest) (*WireIdentity, error)
	// Per-query enforcement decision. Takes the RAW token, re-validated +
	// re-resolved server-side every call — never a client-cached principal.
	Decide(context.Context, *DecisionRequest) (*WireDecision, error)
	// Per-connection schema fragment push on the enforcement channel.
	PushSchemaFragment(context.Context, *SchemaFragmentPush) (*SchemaFragmentAck, error)
	// Proxy-initiated connection close; the control-plane idle-sweep is the backstop.
	CloseConnection(context.Context, *CloseConnectionRequest) (*CloseConnectionResponse, error)
	// Proxy-initiated stream: liveness (stream open == alive) + refresh push.
	Events(*EventsRequest, grpc.ServerStreamingServer[ControlEvent]) error
	// The CP-driven execution channel. PROXY-DIALED bidi: the control-plane nudges the proxy over Events
	// (OpenRunChannel) to open this, so data flows both ways without the control-plane ever dialing into the
	// proxy. It serves web-editor and workflow execution through the same backend + Decide path, streaming
	// the decision and masked rows back.
	RunExec(grpc.BidiStreamingServer[ProxyRunMsg, ControlRunMsg]) error
	// On-demand admin table-browser introspection. Also PROXY-DIALED: request selectors ride the Events
	// nudge and the rich shared TableDetail response returns as JSON on this short-lived channel.
	TableDetailExec(grpc.BidiStreamingServer[ProxyTableDetailMsg, ControlTableDetailMsg]) error
	// Post-execution result-volume report the proxy sends after it finishes relaying one statement's result
	// to the client. Audit-only: it records a completion event chained onto the decision's audit row (never
	// a re-decision), giving the audit monitor the rows/bytes signal the pre-execution decision could not
	// carry. Best-effort — the proxy fires it off the client session's critical path and a failure never
	// affects the query. A DENY relays nothing, so it produces no completion.
	ReportCompletion(context.Context, *CompletionReport) (*emptypb.Empty, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedControlPlaneServer) PushCatalog(context.Context, *CatalogRequest) (*CatalogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushCatalog not implemented")
}
func (UnimplementedControlPlaneServer) ValidateToken(context.Context, *ValidateTokenRequest) (*WireIdentity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedControlPlaneServer) Decide(context.Context, *DecisionRequest) (*WireDecision, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decide not implemented")
}
func (UnimplementedControlPlaneServer) PushSchemaFragment(context.Context, *SchemaFragmentPush) (*SchemaFragmentAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushSchemaFragment not implemented")
}
func (UnimplementedControlPlaneServer) CloseConnection(context.Context, *CloseConnectionRequest) (*CloseConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseConnection not implemented")
}
func (UnimplementedControlPlaneServer) Events(*EventsRequest, grpc.ServerStreamingServer[ControlEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Events not implemented")
}
func (UnimplementedControlPlaneServer) RunExec(grpc.BidiStreamingServer[ProxyRunMsg, ControlRunMsg]) error {
	return status.Errorf(codes.Unimplemented, "method RunExec not implemented")
}
func (UnimplementedControlPlaneServer) TableDetailExec(grpc.BidiStreamingServer[ProxyTableDetailMsg, ControlTableDetailMsg]) error {
	return status.Errorf(codes.Unimplemented, "method TableDetailExec not implemented")
}
func (UnimplementedControlPlaneServer) ReportCompletion(context.Context, *CompletionReport) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportCompletion not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call pancis, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_PushCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).PushCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_PushCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).PushCatalog(ctx, req.(*CatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Decide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Decide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Decide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Decide(ctx, req.(*DecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_PushSchemaFragment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemaFragmentPush)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).PushSchemaFragment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_PushSchemaFragment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).PushSchemaFragment(ctx, req.(*SchemaFragmentPush))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_CloseConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).CloseConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_CloseConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).CloseConnection(ctx, req.(*CloseConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).Events(m, &grpc.GenericServerStream[EventsRequest, ControlEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_EventsServer = grpc.ServerStreamingServer[ControlEvent]

func _ControlPlane_RunExec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServer).RunExec(&grpc.GenericServerStream[ProxyRunMsg, ControlRunMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_RunExecServer = grpc.BidiStreamingServer[ProxyRunMsg, ControlRunMsg]

func _ControlPlane_TableDetailExec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServer).TableDetailExec(&grpc.GenericServerStream[ProxyTableDetailMsg, ControlTableDetailMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_TableDetailExecServer = grpc.BidiStreamingServer[ProxyTableDetailMsg, ControlTableDetailMsg]

func _ControlPlane_ReportCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletionReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ReportCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ReportCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ReportCompletion(ctx, req.(*CompletionReport))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxymonster.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ControlPlane_Register_Handler,
		},
		{
			MethodName: "PushCatalog",
			Handler:    _ControlPlane_PushCatalog_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _ControlPlane_ValidateToken_Handler,
		},
		{
			MethodName: "Decide",
			Handler:    _ControlPlane_Decide_Handler,
		},
		{
			MethodName: "PushSchemaFragment",
			Handler:    _ControlPlane_PushSchemaFragment_Handler,
		},
		{
			MethodName: "CloseConnection",
			Handler:    _ControlPlane_CloseConnection_Handler,
		},
		{
			MethodName: "ReportCompletion",
			Handler:    _ControlPlane_ReportCompletion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _ControlPlane_Events_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RunExec",
			Handler:       _ControlPlane_RunExec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "TableDetailExec",
			Handler:       _ControlPlane_TableDetailExec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "controlplane.proto",
}
