// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const auditEvent = `-- name: AuditEvent :one
SELECT id, ts, kind, principal, roles, datasource, client_addr, statement, decision, failed_stage, masked_columns, pii_touched, latency_ms, detail, effective_namespace, channel, context_tags, action, resource, outcome, rows_returned, bytes_returned, decision_id, chain_version, prev_hash, row_hash FROM audit_event WHERE id = $1
`

func (q *Queries) AuditEvent(ctx context.Context, id int64) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, auditEvent, id)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.Kind,
		&i.Principal,
		&i.Roles,
		&i.Datasource,
		&i.ClientAddr,
		&i.Statement,
		&i.Decision,
		&i.FailedStage,
		&i.MaskedColumns,
		&i.PiiTouched,
		&i.LatencyMs,
		&i.Detail,
		&i.EffectiveNamespace,
		&i.Channel,
		&i.ContextTags,
		&i.Action,
		&i.Resource,
		&i.Outcome,
		&i.RowsReturned,
		&i.BytesReturned,
		&i.DecisionID,
		&i.ChainVersion,
		&i.PrevHash,
		&i.RowHash,
	)
	return i, err
}

const auditLog = `-- name: AuditLog :many
SELECT id, ts, kind, principal, roles, datasource, client_addr, statement, decision, failed_stage, masked_columns, pii_touched, latency_ms, detail, effective_namespace, channel, context_tags, action, resource, outcome, rows_returned, bytes_returned, decision_id, chain_version, prev_hash, row_hash FROM audit_event ORDER BY ts DESC LIMIT $1
`

func (q *Queries) AuditLog(ctx context.Context, limit int32) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, auditLog, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Kind,
			&i.Principal,
			&i.Roles,
			&i.Datasource,
			&i.ClientAddr,
			&i.Statement,
			&i.Decision,
			&i.FailedStage,
			&i.MaskedColumns,
			&i.PiiTouched,
			&i.LatencyMs,
			&i.Detail,
			&i.EffectiveNamespace,
			&i.Channel,
			&i.ContextTags,
			&i.Action,
			&i.Resource,
			&i.Outcome,
			&i.RowsReturned,
			&i.BytesReturned,
			&i.DecisionID,
			&i.ChainVersion,
			&i.PrevHash,
			&i.RowHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const auditLogOf = `-- name: AuditLogOf :many
SELECT id, ts, kind, principal, roles, datasource, client_addr, statement, decision, failed_stage, masked_columns, pii_touched, latency_ms, detail, effective_namespace, channel, context_tags, action, resource, outcome, rows_returned, bytes_returned, decision_id, chain_version, prev_hash, row_hash FROM audit_event WHERE principal = $1 ORDER BY ts DESC LIMIT $2
`

type AuditLogOfParams struct {
	Principal string
	Limit     int32
}

func (q *Queries) AuditLogOf(ctx context.Context, arg AuditLogOfParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, auditLogOf, arg.Principal, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Kind,
			&i.Principal,
			&i.Roles,
			&i.Datasource,
			&i.ClientAddr,
			&i.Statement,
			&i.Decision,
			&i.FailedStage,
			&i.MaskedColumns,
			&i.PiiTouched,
			&i.LatencyMs,
			&i.Detail,
			&i.EffectiveNamespace,
			&i.Channel,
			&i.ContextTags,
			&i.Action,
			&i.Resource,
			&i.Outcome,
			&i.RowsReturned,
			&i.BytesReturned,
			&i.DecisionID,
			&i.ChainVersion,
			&i.PrevHash,
			&i.RowHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
