// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authz.sql

package db

import (
	"context"
)

const datasourceNameTags = `-- name: DatasourceNameTags :one
SELECT name, tags FROM datasource WHERE id = $1 AND deleted_at IS NULL
`

type DatasourceNameTagsRow struct {
	Name string
	Tags []string
}

func (q *Queries) DatasourceNameTags(ctx context.Context, id int64) (DatasourceNameTagsRow, error) {
	row := q.db.QueryRow(ctx, datasourceNameTags, id)
	var i DatasourceNameTagsRow
	err := row.Scan(&i.Name, &i.Tags)
	return i, err
}

const enabledPolicies = `-- name: EnabledPolicies :many
SELECT id, cedar_src FROM policy WHERE enabled AND deleted_at IS NULL ORDER BY id
`

type EnabledPoliciesRow struct {
	ID       int64
	CedarSrc string
}

func (q *Queries) EnabledPolicies(ctx context.Context) ([]EnabledPoliciesRow, error) {
	rows, err := q.db.Query(ctx, enabledPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnabledPoliciesRow{}
	for rows.Next() {
		var i EnabledPoliciesRow
		if err := rows.Scan(&i.ID, &i.CedarSrc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isDeactivated = `-- name: IsDeactivated :one
SELECT EXISTS(SELECT 1 FROM app_user WHERE principal = $1 AND NOT active)
`

func (q *Queries) IsDeactivated(ctx context.Context, principal string) (bool, error) {
	row := q.db.QueryRow(ctx, isDeactivated, principal)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const policyFingerprint = `-- name: PolicyFingerprint :one
SELECT coalesce(md5(string_agg(id || '@' || updated_at, ',' ORDER BY id)), '')::text AS fingerprint
FROM policy WHERE enabled AND deleted_at IS NULL
`

func (q *Queries) PolicyFingerprint(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, policyFingerprint)
	var fingerprint string
	err := row.Scan(&fingerprint)
	return fingerprint, err
}

const principalRoles = `-- name: PrincipalRoles :many
SELECT r.name FROM principal_role pr JOIN app_role r ON r.id = pr.role_id AND r.deleted_at IS NULL
WHERE pr.principal = $1
UNION
SELECT r.name FROM access_grant ag JOIN app_role r ON r.id = ag.role_id AND r.deleted_at IS NULL
WHERE ag.principal = $1 AND ag.revoked_at IS NULL AND (ag.expires_at IS NULL OR ag.expires_at > now())
UNION
SELECT r.name FROM app_user u
JOIN group_member gm ON gm.user_id = u.id
JOIN app_group g ON g.id = gm.group_id AND g.deleted_at IS NULL
JOIN group_role gr ON gr.group_id = gm.group_id
JOIN app_role r ON r.id = gr.role_id AND r.deleted_at IS NULL
WHERE u.principal = $1 AND u.active
`

func (q *Queries) PrincipalRoles(ctx context.Context, principal string) ([]string, error) {
	rows, err := q.db.Query(ctx, principalRoles, principal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
