// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorize.sql

package db

import (
	"context"
)

const requestCaller = `-- name: RequestCaller :one
SELECT principal, kind FROM proxy_token
WHERE token_hash = $1 AND kind IN ('SESSION', 'USER', 'EDITOR', 'APPROVER_EXEC')
  AND revoked_at IS NULL AND expires_at > now()
`

type RequestCallerRow struct {
	Principal string
	Kind      string
}

func (q *Queries) RequestCaller(ctx context.Context, tokenHash string) (RequestCallerRow, error) {
	row := q.db.QueryRow(ctx, requestCaller, tokenHash)
	var i RequestCallerRow
	err := row.Scan(&i.Principal, &i.Kind)
	return i, err
}

const requestDatasource = `-- name: RequestDatasource :one
SELECT name, engine, db_name, current_catalog_name, tags FROM datasource WHERE name = $1 AND deleted_at IS NULL
`

type RequestDatasourceRow struct {
	Name               string
	Engine             string
	DbName             string
	CurrentCatalogName *string
	Tags               []string
}

func (q *Queries) RequestDatasource(ctx context.Context, name string) (RequestDatasourceRow, error) {
	row := q.db.QueryRow(ctx, requestDatasource, name)
	var i RequestDatasourceRow
	err := row.Scan(
		&i.Name,
		&i.Engine,
		&i.DbName,
		&i.CurrentCatalogName,
		&i.Tags,
	)
	return i, err
}
