// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
)

const addDirectRole = `-- name: AddDirectRole :exec
INSERT INTO principal_role (principal, role_id) VALUES ($1, $2)
ON CONFLICT (principal, role_id) DO UPDATE SET principal = EXCLUDED.principal
`

type AddDirectRoleParams struct {
	Principal string
	RoleID    int64
}

func (q *Queries) AddDirectRole(ctx context.Context, arg AddDirectRoleParams) error {
	_, err := q.db.Exec(ctx, addDirectRole, arg.Principal, arg.RoleID)
	return err
}

const deleteDirectRoles = `-- name: DeleteDirectRoles :exec
DELETE FROM principal_role WHERE principal = $1
AND role_id IN (SELECT id FROM app_role WHERE deleted_at IS NULL)
`

func (q *Queries) DeleteDirectRoles(ctx context.Context, principal string) error {
	_, err := q.db.Exec(ctx, deleteDirectRoles, principal)
	return err
}

const liveRoleID = `-- name: LiveRoleID :one
SELECT id FROM app_role WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) LiveRoleID(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, liveRoleID, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
