// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cedardiff.sql

package db

import (
	"context"
)

const cedarDiffDatasourceTags = `-- name: CedarDiffDatasourceTags :many
SELECT name, tags FROM datasource
`

type CedarDiffDatasourceTagsRow struct {
	Name string
	Tags []string
}

func (q *Queries) CedarDiffDatasourceTags(ctx context.Context) ([]CedarDiffDatasourceTagsRow, error) {
	rows, err := q.db.Query(ctx, cedarDiffDatasourceTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CedarDiffDatasourceTagsRow{}
	for rows.Next() {
		var i CedarDiffDatasourceTagsRow
		if err := rows.Scan(&i.Name, &i.Tags); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cedarDiffDatasources = `-- name: CedarDiffDatasources :many
SELECT id FROM datasource ORDER BY id
`

func (q *Queries) CedarDiffDatasources(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, cedarDiffDatasources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cedarDiffGrants = `-- name: CedarDiffGrants :many
SELECT ag.principal, ag.id, r.name FROM access_grant ag JOIN app_role r ON r.id = ag.role_id
`

type CedarDiffGrantsRow struct {
	Principal string
	ID        int64
	Name      string
}

func (q *Queries) CedarDiffGrants(ctx context.Context) ([]CedarDiffGrantsRow, error) {
	rows, err := q.db.Query(ctx, cedarDiffGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CedarDiffGrantsRow{}
	for rows.Next() {
		var i CedarDiffGrantsRow
		if err := rows.Scan(&i.Principal, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cedarDiffPolicySources = `-- name: CedarDiffPolicySources :many
SELECT cedar_src FROM policy
`

func (q *Queries) CedarDiffPolicySources(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, cedarDiffPolicySources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var cedar_src string
		if err := rows.Scan(&cedar_src); err != nil {
			return nil, err
		}
		items = append(items, cedar_src)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cedarDiffPrincipals = `-- name: CedarDiffPrincipals :many
SELECT principal FROM app_user UNION SELECT principal FROM principal_role
UNION SELECT principal FROM access_grant UNION SELECT principal FROM access_request
`

func (q *Queries) CedarDiffPrincipals(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, cedarDiffPrincipals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var principal string
		if err := rows.Scan(&principal); err != nil {
			return nil, err
		}
		items = append(items, principal)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cedarDiffRequests = `-- name: CedarDiffRequests :many
SELECT ar.principal, ar.decided_by, d.name AS datasource_name, r.name AS role_name,
(SELECT qr.executed_by FROM query_result qr WHERE qr.task_id = ar.id ORDER BY qr.ordinal LIMIT 1) AS executed_by
FROM access_request ar LEFT JOIN app_role r ON r.id = ar.role_id LEFT JOIN datasource d ON d.id = ar.datasource_id
`

type CedarDiffRequestsRow struct {
	Principal      string
	DecidedBy      *string
	DatasourceName *string
	RoleName       *string
	ExecutedBy     *string
}

func (q *Queries) CedarDiffRequests(ctx context.Context) ([]CedarDiffRequestsRow, error) {
	rows, err := q.db.Query(ctx, cedarDiffRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CedarDiffRequestsRow{}
	for rows.Next() {
		var i CedarDiffRequestsRow
		if err := rows.Scan(
			&i.Principal,
			&i.DecidedBy,
			&i.DatasourceName,
			&i.RoleName,
			&i.ExecutedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
