// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classification.sql

package db

import (
	"context"
)

const clearClassification = `-- name: ClearClassification :execrows
DELETE FROM column_classification WHERE datasource_id = $1 AND schema_name = $2
AND table_name = $3 AND column_name = $4 AND catalog_name = $5
`

type ClearClassificationParams struct {
	DatasourceID int64
	SchemaName   string
	TableName    string
	ColumnName   string
	CatalogName  string
}

func (q *Queries) ClearClassification(ctx context.Context, arg ClearClassificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearClassification,
		arg.DatasourceID,
		arg.SchemaName,
		arg.TableName,
		arg.ColumnName,
		arg.CatalogName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const liveMaskFnName = `-- name: LiveMaskFnName :one
SELECT name FROM mask_fn WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) LiveMaskFnName(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, liveMaskFnName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const setClassification = `-- name: SetClassification :exec
INSERT INTO column_classification
(datasource_id, schema_name, table_name, column_name, tags, mask_fn_id, updated_at, catalog_name)
VALUES ($1, $2, $3, $4, $5::jsonb, $6, now(), $7)
ON CONFLICT (datasource_id, catalog_name, schema_name, table_name, column_name)
DO UPDATE SET tags = EXCLUDED.tags, mask_fn_id = EXCLUDED.mask_fn_id, updated_at = now()
`

type SetClassificationParams struct {
	DatasourceID int64
	SchemaName   string
	TableName    string
	ColumnName   string
	Tags         []byte
	MaskFnID     *int64
	CatalogName  string
}

func (q *Queries) SetClassification(ctx context.Context, arg SetClassificationParams) error {
	_, err := q.db.Exec(ctx, setClassification,
		arg.DatasourceID,
		arg.SchemaName,
		arg.TableName,
		arg.ColumnName,
		arg.Tags,
		arg.MaskFnID,
		arg.CatalogName,
	)
	return err
}
