// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: completion.sql

package db

import (
	"context"
	"time"
)

const claimWireTask = `-- name: ClaimWireTask :execrows
UPDATE access_request SET status = 'EXECUTING', executing_at = $1
WHERE id = $2 AND kind = 'QUERY' AND status = 'APPROVED'
`

type ClaimWireTaskParams struct {
	ExecutingAt *time.Time
	ID          int64
}

func (q *Queries) ClaimWireTask(ctx context.Context, arg ClaimWireTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimWireTask, arg.ExecutingAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decisionEvent = `-- name: DecisionEvent :one
SELECT principal, datasource, statement, decision, channel FROM audit_event WHERE id = $1
`

type DecisionEventRow struct {
	Principal  string
	Datasource string
	Statement  string
	Decision   string
	Channel    *string
}

func (q *Queries) DecisionEvent(ctx context.Context, id int64) (DecisionEventRow, error) {
	row := q.db.QueryRow(ctx, decisionEvent, id)
	var i DecisionEventRow
	err := row.Scan(
		&i.Principal,
		&i.Datasource,
		&i.Statement,
		&i.Decision,
		&i.Channel,
	)
	return i, err
}

const settleWireTaskExecuted = `-- name: SettleWireTaskExecuted :execrows
UPDATE access_request SET status = 'EXECUTED', executed_at = $1
WHERE id = $2 AND kind = 'QUERY' AND status = 'EXECUTING'
`

type SettleWireTaskExecutedParams struct {
	ExecutedAt *time.Time
	ID         int64
}

func (q *Queries) SettleWireTaskExecuted(ctx context.Context, arg SettleWireTaskExecutedParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleWireTaskExecuted, arg.ExecutedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settleWireTaskFailed = `-- name: SettleWireTaskFailed :execrows
UPDATE access_request SET status = 'FAILED' WHERE id = $1 AND kind = 'QUERY' AND status = 'EXECUTING'
`

func (q *Queries) SettleWireTaskFailed(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, settleWireTaskFailed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const wireTaskOfDecision = `-- name: WireTaskOfDecision :one
SELECT id FROM access_request WHERE kind = 'QUERY' AND creator_kind = 'WIRE' AND source_decision_id = $1
`

func (q *Queries) WireTaskOfDecision(ctx context.Context, sourceDecisionID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, wireTaskOfDecision, sourceDecisionID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
