// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: datasources.sql

package db

import (
	"context"
	"time"
)

const datasource = `-- name: Datasource :one
SELECT id, name, engine, host, port, db_name, tags, default_schemas, mysql_lower_case_table_names,
       catalog_synced_at, last_seen_at, engine_version, advertise_addr, advertise_cert_chain,
       advertise_wire_tls, current_catalog_name, connection_info, description
FROM datasource WHERE deleted_at IS NULL AND id = $1
`

type DatasourceRow struct {
	ID                       int64
	Name                     string
	Engine                   string
	Host                     string
	Port                     int32
	DbName                   string
	Tags                     []string
	DefaultSchemas           []string
	MysqlLowerCaseTableNames *int32
	CatalogSyncedAt          *time.Time
	LastSeenAt               *time.Time
	EngineVersion            *string
	AdvertiseAddr            *string
	AdvertiseCertChain       *string
	AdvertiseWireTls         bool
	CurrentCatalogName       *string
	ConnectionInfo           []byte
	Description              string
}

func (q *Queries) Datasource(ctx context.Context, id int64) (DatasourceRow, error) {
	row := q.db.QueryRow(ctx, datasource, id)
	var i DatasourceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Host,
		&i.Port,
		&i.DbName,
		&i.Tags,
		&i.DefaultSchemas,
		&i.MysqlLowerCaseTableNames,
		&i.CatalogSyncedAt,
		&i.LastSeenAt,
		&i.EngineVersion,
		&i.AdvertiseAddr,
		&i.AdvertiseCertChain,
		&i.AdvertiseWireTls,
		&i.CurrentCatalogName,
		&i.ConnectionInfo,
		&i.Description,
	)
	return i, err
}

const datasources = `-- name: Datasources :many
SELECT id, name, engine, host, port, db_name, tags, default_schemas, mysql_lower_case_table_names,
       catalog_synced_at, last_seen_at, engine_version, advertise_addr, advertise_cert_chain,
       advertise_wire_tls, current_catalog_name, connection_info, description
FROM datasource WHERE deleted_at IS NULL ORDER BY id
`

type DatasourcesRow struct {
	ID                       int64
	Name                     string
	Engine                   string
	Host                     string
	Port                     int32
	DbName                   string
	Tags                     []string
	DefaultSchemas           []string
	MysqlLowerCaseTableNames *int32
	CatalogSyncedAt          *time.Time
	LastSeenAt               *time.Time
	EngineVersion            *string
	AdvertiseAddr            *string
	AdvertiseCertChain       *string
	AdvertiseWireTls         bool
	CurrentCatalogName       *string
	ConnectionInfo           []byte
	Description              string
}

func (q *Queries) Datasources(ctx context.Context) ([]DatasourcesRow, error) {
	rows, err := q.db.Query(ctx, datasources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatasourcesRow{}
	for rows.Next() {
		var i DatasourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Engine,
			&i.Host,
			&i.Port,
			&i.DbName,
			&i.Tags,
			&i.DefaultSchemas,
			&i.MysqlLowerCaseTableNames,
			&i.CatalogSyncedAt,
			&i.LastSeenAt,
			&i.EngineVersion,
			&i.AdvertiseAddr,
			&i.AdvertiseCertChain,
			&i.AdvertiseWireTls,
			&i.CurrentCatalogName,
			&i.ConnectionInfo,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
