// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: datasources.sql

package db

import (
	"context"
	"time"
)

const createDatasource = `-- name: CreateDatasource :one
INSERT INTO datasource (name, engine, host, port, db_name) VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateDatasourceParams struct {
	Name   string
	Engine string
	Host   string
	Port   int
	DbName string
}

func (q *Queries) CreateDatasource(ctx context.Context, arg CreateDatasourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, createDatasource,
		arg.Name,
		arg.Engine,
		arg.Host,
		arg.Port,
		arg.DbName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const datasource = `-- name: Datasource :one
SELECT id, name, engine, host, port, db_name, tags, default_schemas, mysql_lower_case_table_names,
       catalog_synced_at, last_seen_at, engine_version, advertise_addr, advertise_cert_chain,
       advertise_wire_tls, current_catalog_name, connection_info, description
FROM datasource WHERE deleted_at IS NULL AND id = $1
`

type DatasourceRow struct {
	ID                       int64
	Name                     string
	Engine                   string
	Host                     string
	Port                     int
	DbName                   string
	Tags                     []string
	DefaultSchemas           []string
	MysqlLowerCaseTableNames *int32
	CatalogSyncedAt          *time.Time
	LastSeenAt               *time.Time
	EngineVersion            *string
	AdvertiseAddr            *string
	AdvertiseCertChain       *string
	AdvertiseWireTls         bool
	CurrentCatalogName       *string
	ConnectionInfo           []byte
	Description              string
}

func (q *Queries) Datasource(ctx context.Context, id int64) (DatasourceRow, error) {
	row := q.db.QueryRow(ctx, datasource, id)
	var i DatasourceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Host,
		&i.Port,
		&i.DbName,
		&i.Tags,
		&i.DefaultSchemas,
		&i.MysqlLowerCaseTableNames,
		&i.CatalogSyncedAt,
		&i.LastSeenAt,
		&i.EngineVersion,
		&i.AdvertiseAddr,
		&i.AdvertiseCertChain,
		&i.AdvertiseWireTls,
		&i.CurrentCatalogName,
		&i.ConnectionInfo,
		&i.Description,
	)
	return i, err
}

const datasourceHasActiveRequests = `-- name: DatasourceHasActiveRequests :one
SELECT EXISTS (SELECT 1 FROM access_request WHERE datasource_id = $1 AND (
(kind = 'ROLE' AND status = 'PENDING') OR (kind = 'QUERY' AND status IN ('PENDING', 'EXECUTING'))))
`

func (q *Queries) DatasourceHasActiveRequests(ctx context.Context, datasourceID *int64) (bool, error) {
	row := q.db.QueryRow(ctx, datasourceHasActiveRequests, datasourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const datasources = `-- name: Datasources :many
SELECT id, name, engine, host, port, db_name, tags, default_schemas, mysql_lower_case_table_names,
       catalog_synced_at, last_seen_at, engine_version, advertise_addr, advertise_cert_chain,
       advertise_wire_tls, current_catalog_name, connection_info, description
FROM datasource WHERE deleted_at IS NULL ORDER BY id
`

type DatasourcesRow struct {
	ID                       int64
	Name                     string
	Engine                   string
	Host                     string
	Port                     int
	DbName                   string
	Tags                     []string
	DefaultSchemas           []string
	MysqlLowerCaseTableNames *int32
	CatalogSyncedAt          *time.Time
	LastSeenAt               *time.Time
	EngineVersion            *string
	AdvertiseAddr            *string
	AdvertiseCertChain       *string
	AdvertiseWireTls         bool
	CurrentCatalogName       *string
	ConnectionInfo           []byte
	Description              string
}

func (q *Queries) Datasources(ctx context.Context) ([]DatasourcesRow, error) {
	rows, err := q.db.Query(ctx, datasources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatasourcesRow{}
	for rows.Next() {
		var i DatasourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Engine,
			&i.Host,
			&i.Port,
			&i.DbName,
			&i.Tags,
			&i.DefaultSchemas,
			&i.MysqlLowerCaseTableNames,
			&i.CatalogSyncedAt,
			&i.LastSeenAt,
			&i.EngineVersion,
			&i.AdvertiseAddr,
			&i.AdvertiseCertChain,
			&i.AdvertiseWireTls,
			&i.CurrentCatalogName,
			&i.ConnectionInfo,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDatasource = `-- name: DeleteDatasource :execrows
UPDATE datasource SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteDatasource(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDatasource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockDatasourceEngine = `-- name: LockDatasourceEngine :one
SELECT engine, db_name FROM datasource WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

type LockDatasourceEngineRow struct {
	Engine string
	DbName string
}

func (q *Queries) LockDatasourceEngine(ctx context.Context, id int64) (LockDatasourceEngineRow, error) {
	row := q.db.QueryRow(ctx, lockDatasourceEngine, id)
	var i LockDatasourceEngineRow
	err := row.Scan(&i.Engine, &i.DbName)
	return i, err
}

const resetDatasourceCatalog = `-- name: ResetDatasourceCatalog :exec
UPDATE datasource SET catalog = NULL, current_catalog_name = NULL, catalog_synced_at = NULL,
default_schemas = '[]'::jsonb, mysql_lower_case_table_names = NULL WHERE id = $1
`

func (q *Queries) ResetDatasourceCatalog(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resetDatasourceCatalog, id)
	return err
}

const updateDatasource = `-- name: UpdateDatasource :exec
UPDATE datasource SET name = $1, engine = $2, host = $3, port = $4, db_name = $5
WHERE id = $6 AND deleted_at IS NULL
`

type UpdateDatasourceParams struct {
	Name   string
	Engine string
	Host   string
	Port   int
	DbName string
	ID     int64
}

func (q *Queries) UpdateDatasource(ctx context.Context, arg UpdateDatasourceParams) error {
	_, err := q.db.Exec(ctx, updateDatasource,
		arg.Name,
		arg.Engine,
		arg.Host,
		arg.Port,
		arg.DbName,
		arg.ID,
	)
	return err
}
