// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device.sql

package db

import (
	"context"
	"time"
)

const approveDeviceLogin = `-- name: ApproveDeviceLogin :execrows
UPDATE device_login SET status = 'APPROVED', principal = $1, refresh_token_enc = $2, elevated_until = $3
WHERE handle = $4 AND status = 'PENDING' AND expires_at > now()
`

type ApproveDeviceLoginParams struct {
	Principal       *string
	RefreshTokenEnc []byte
	ElevatedUntil   *time.Time
	Handle          string
}

func (q *Queries) ApproveDeviceLogin(ctx context.Context, arg ApproveDeviceLoginParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveDeviceLogin,
		arg.Principal,
		arg.RefreshTokenEnc,
		arg.ElevatedUntil,
		arg.Handle,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeDeviceLogin = `-- name: ConsumeDeviceLogin :execrows
UPDATE device_login SET status = 'CONSUMED' WHERE handle = $1 AND status = 'APPROVED' AND expires_at > now()
`

func (q *Queries) ConsumeDeviceLogin(ctx context.Context, handle string) (int64, error) {
	result, err := q.db.Exec(ctx, consumeDeviceLogin, handle)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDaemonSession = `-- name: CreateDaemonSession :one
INSERT INTO principal_session
(principal, handle, refresh_token_enc, ttl_seconds, absolute_expires_at, liveness_status, renewal_token_hash, kind, scopes, elevated_until)
VALUES ($1, $2, $3, $4, now() + make_interval(secs => $5), 'ACTIVE', $6, 'DAEMON', $7, $8)
RETURNING id, absolute_expires_at
`

type CreateDaemonSessionParams struct {
	Principal        string
	Handle           *string
	RefreshTokenEnc  []byte
	TtlSeconds       *int64
	WindowSeconds    float64
	RenewalTokenHash *string
	Scopes           *string
	ElevatedUntil    *time.Time
}

type CreateDaemonSessionRow struct {
	ID                int64
	AbsoluteExpiresAt time.Time
}

func (q *Queries) CreateDaemonSession(ctx context.Context, arg CreateDaemonSessionParams) (CreateDaemonSessionRow, error) {
	row := q.db.QueryRow(ctx, createDaemonSession,
		arg.Principal,
		arg.Handle,
		arg.RefreshTokenEnc,
		arg.TtlSeconds,
		arg.WindowSeconds,
		arg.RenewalTokenHash,
		arg.Scopes,
		arg.ElevatedUntil,
	)
	var i CreateDaemonSessionRow
	err := row.Scan(&i.ID, &i.AbsoluteExpiresAt)
	return i, err
}

const createDeviceLogin = `-- name: CreateDeviceLogin :exec
INSERT INTO device_login (handle, user_code, interval_sec, ttl_seconds, expires_at, scopes)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateDeviceLoginParams struct {
	Handle      string
	UserCode    *string
	IntervalSec int32
	TtlSeconds  int64
	ExpiresAt   time.Time
	Scopes      string
}

func (q *Queries) CreateDeviceLogin(ctx context.Context, arg CreateDeviceLoginParams) error {
	_, err := q.db.Exec(ctx, createDeviceLogin,
		arg.Handle,
		arg.UserCode,
		arg.IntervalSec,
		arg.TtlSeconds,
		arg.ExpiresAt,
		arg.Scopes,
	)
	return err
}

const daemonSession = `-- name: DaemonSession :one
SELECT id, principal, ttl_seconds::bigint AS ttl_seconds, liveness_status, created_at, coalesce(scopes, '') AS scopes, elevated_until
FROM principal_session WHERE kind = 'DAEMON' AND id = $1
`

type DaemonSessionRow struct {
	ID             int64
	Principal      string
	TtlSeconds     int64
	LivenessStatus string
	CreatedAt      time.Time
	Scopes         string
	ElevatedUntil  *time.Time
}

func (q *Queries) DaemonSession(ctx context.Context, id int64) (DaemonSessionRow, error) {
	row := q.db.QueryRow(ctx, daemonSession, id)
	var i DaemonSessionRow
	err := row.Scan(
		&i.ID,
		&i.Principal,
		&i.TtlSeconds,
		&i.LivenessStatus,
		&i.CreatedAt,
		&i.Scopes,
		&i.ElevatedUntil,
	)
	return i, err
}

const daemonSessionByRenewal = `-- name: DaemonSessionByRenewal :one
SELECT id, principal, ttl_seconds::bigint AS ttl_seconds, liveness_status, created_at, coalesce(scopes, '') AS scopes, elevated_until
FROM principal_session WHERE kind = 'DAEMON' AND renewal_token_hash = $1
`

type DaemonSessionByRenewalRow struct {
	ID             int64
	Principal      string
	TtlSeconds     int64
	LivenessStatus string
	CreatedAt      time.Time
	Scopes         string
	ElevatedUntil  *time.Time
}

func (q *Queries) DaemonSessionByRenewal(ctx context.Context, renewalTokenHash *string) (DaemonSessionByRenewalRow, error) {
	row := q.db.QueryRow(ctx, daemonSessionByRenewal, renewalTokenHash)
	var i DaemonSessionByRenewalRow
	err := row.Scan(
		&i.ID,
		&i.Principal,
		&i.TtlSeconds,
		&i.LivenessStatus,
		&i.CreatedAt,
		&i.Scopes,
		&i.ElevatedUntil,
	)
	return i, err
}

const daemonWithinWindow = `-- name: DaemonWithinWindow :one
SELECT absolute_expires_at > clock_timestamp() AS within FROM principal_session WHERE id = $1
`

func (q *Queries) DaemonWithinWindow(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, daemonWithinWindow, id)
	var within bool
	err := row.Scan(&within)
	return within, err
}

const deviceLoginByHandle = `-- name: DeviceLoginByHandle :one
SELECT id, handle, user_code, ttl_seconds, status, principal, refresh_token_enc, expires_at,
coalesce(scopes, '') AS scopes, elevated_until FROM device_login WHERE handle = $1
`

type DeviceLoginByHandleRow struct {
	ID              int64
	Handle          string
	UserCode        *string
	TtlSeconds      int64
	Status          string
	Principal       *string
	RefreshTokenEnc []byte
	ExpiresAt       time.Time
	Scopes          string
	ElevatedUntil   *time.Time
}

func (q *Queries) DeviceLoginByHandle(ctx context.Context, handle string) (DeviceLoginByHandleRow, error) {
	row := q.db.QueryRow(ctx, deviceLoginByHandle, handle)
	var i DeviceLoginByHandleRow
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.UserCode,
		&i.TtlSeconds,
		&i.Status,
		&i.Principal,
		&i.RefreshTokenEnc,
		&i.ExpiresAt,
		&i.Scopes,
		&i.ElevatedUntil,
	)
	return i, err
}

const deviceLoginByUserCode = `-- name: DeviceLoginByUserCode :one
SELECT id, handle, user_code, ttl_seconds, status, principal, refresh_token_enc, expires_at,
coalesce(scopes, '') AS scopes, elevated_until FROM device_login WHERE user_code = $1
`

type DeviceLoginByUserCodeRow struct {
	ID              int64
	Handle          string
	UserCode        *string
	TtlSeconds      int64
	Status          string
	Principal       *string
	RefreshTokenEnc []byte
	ExpiresAt       time.Time
	Scopes          string
	ElevatedUntil   *time.Time
}

func (q *Queries) DeviceLoginByUserCode(ctx context.Context, userCode *string) (DeviceLoginByUserCodeRow, error) {
	row := q.db.QueryRow(ctx, deviceLoginByUserCode, userCode)
	var i DeviceLoginByUserCodeRow
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.UserCode,
		&i.TtlSeconds,
		&i.Status,
		&i.Principal,
		&i.RefreshTokenEnc,
		&i.ExpiresAt,
		&i.Scopes,
		&i.ElevatedUntil,
	)
	return i, err
}

const endDaemonSession = `-- name: EndDaemonSession :one
UPDATE principal_session
SET ended_at = now(), ended_reason = 'SIGNED_OUT', liveness_status = 'INACTIVE', absolute_expires_at = LEAST(absolute_expires_at, now())
WHERE id = $1 AND kind = 'DAEMON' AND ended_at IS NULL
RETURNING principal
`

func (q *Queries) EndDaemonSession(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, endDaemonSession, id)
	var principal string
	err := row.Scan(&principal)
	return principal, err
}

const issueSessionToken = `-- name: IssueSessionToken :one
INSERT INTO proxy_token (token_hash, kind, principal, roles, expires_at, principal_session_id)
VALUES ($1, 'SESSION', $2, '[]'::jsonb, now() + ($3::bigint * interval '1 second'), $4) RETURNING id, expires_at
`

type IssueSessionTokenParams struct {
	TokenHash          string
	Principal          string
	Ttl                int64
	PrincipalSessionID *int64
}

type IssueSessionTokenRow struct {
	ID        int64
	ExpiresAt time.Time
}

func (q *Queries) IssueSessionToken(ctx context.Context, arg IssueSessionTokenParams) (IssueSessionTokenRow, error) {
	row := q.db.QueryRow(ctx, issueSessionToken,
		arg.TokenHash,
		arg.Principal,
		arg.Ttl,
		arg.PrincipalSessionID,
	)
	var i IssueSessionTokenRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const mintMcpAccessToken = `-- name: MintMcpAccessToken :one
INSERT INTO proxy_token
(token_hash, kind, principal, roles, expires_at, resource, client_id, scope, refresh_family, consent_id, principal_session_id)
VALUES ($1, 'MCP_ACCESS', $2, '[]'::jsonb, $3, $4, $5, $6, $7, $8, $9) RETURNING id
`

type MintMcpAccessTokenParams struct {
	TokenHash          string
	Principal          string
	ExpiresAt          time.Time
	Resource           *string
	ClientID           *string
	Scope              *string
	RefreshFamily      *string
	ConsentID          *int64
	PrincipalSessionID *int64
}

func (q *Queries) MintMcpAccessToken(ctx context.Context, arg MintMcpAccessTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, mintMcpAccessToken,
		arg.TokenHash,
		arg.Principal,
		arg.ExpiresAt,
		arg.Resource,
		arg.ClientID,
		arg.Scope,
		arg.RefreshFamily,
		arg.ConsentID,
		arg.PrincipalSessionID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const pmonConsent = `-- name: PmonConsent :one
INSERT INTO oauth_consent (principal, client_id, resource, scope) VALUES ($1, $2, $3, $4)
ON CONFLICT (principal, client_id, resource, scope) WHERE revoked_at IS NULL DO UPDATE SET updated_at = now()
RETURNING id
`

type PmonConsentParams struct {
	Principal string
	ClientID  string
	Resource  string
	Scope     string
}

func (q *Queries) PmonConsent(ctx context.Context, arg PmonConsentParams) (int64, error) {
	row := q.db.QueryRow(ctx, pmonConsent,
		arg.Principal,
		arg.ClientID,
		arg.Resource,
		arg.Scope,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const retireSessionTokens = `-- name: RetireSessionTokens :exec
UPDATE proxy_token SET retired_at = now()
WHERE principal_session_id = $1 AND kind = 'SESSION' AND revoked_at IS NULL AND retired_at IS NULL
`

func (q *Queries) RetireSessionTokens(ctx context.Context, principalSessionID *int64) error {
	_, err := q.db.Exec(ctx, retireSessionTokens, principalSessionID)
	return err
}

const revokeDaemonTokens = `-- name: RevokeDaemonTokens :many
UPDATE proxy_token SET revoked_at = now()
WHERE principal_session_id = $1 AND revoked_at IS NULL AND (kind <> 'SESSION' OR NOT $2::boolean)
RETURNING consent_id
`

type RevokeDaemonTokensParams struct {
	PrincipalSessionID *int64
	Replaced           bool
}

func (q *Queries) RevokeDaemonTokens(ctx context.Context, arg RevokeDaemonTokensParams) ([]*int64, error) {
	rows, err := q.db.Query(ctx, revokeDaemonTokens, arg.PrincipalSessionID, arg.Replaced)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*int64{}
	for rows.Next() {
		var consent_id *int64
		if err := rows.Scan(&consent_id); err != nil {
			return nil, err
		}
		items = append(items, consent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOrphanConsents = `-- name: RevokeOrphanConsents :exec
UPDATE oauth_consent c SET revoked_at = now(), updated_at = now()
WHERE c.id = ANY($1::bigint[]) AND c.revoked_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM proxy_token t WHERE t.consent_id = c.id AND t.revoked_at IS NULL AND t.expires_at > now())
`

func (q *Queries) RevokeOrphanConsents(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, revokeOrphanConsents, ids)
	return err
}

const webSessionRefreshToken = `-- name: WebSessionRefreshToken :one
SELECT refresh_token_enc FROM principal_session
WHERE id = $1 AND kind = 'WEB' AND ended_at IS NULL
  AND absolute_expires_at > now() AND (idle_expires_at IS NULL OR idle_expires_at > now())
`

func (q *Queries) WebSessionRefreshToken(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, webSessionRefreshToken, id)
	var refresh_token_enc []byte
	err := row.Scan(&refresh_token_enc)
	return refresh_token_enc, err
}
