// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package db

import (
	"context"
	"time"
)

const deleteQueryHistory = `-- name: DeleteQueryHistory :exec
DELETE FROM query_history WHERE principal = $1
`

func (q *Queries) DeleteQueryHistory(ctx context.Context, principal string) error {
	_, err := q.db.Exec(ctx, deleteQueryHistory, principal)
	return err
}

const queryHistory = `-- name: QueryHistory :many
SELECT sql, datasource_id, created_at FROM (
    SELECT DISTINCT ON (sql) sql, datasource_id, created_at
    FROM query_history WHERE principal = $1
    ORDER BY sql, created_at DESC
) q
ORDER BY created_at DESC
LIMIT $2
`

type QueryHistoryParams struct {
	Principal string
	Limit     int32
}

type QueryHistoryRow struct {
	Sql          string
	DatasourceID *int64
	CreatedAt    time.Time
}

func (q *Queries) QueryHistory(ctx context.Context, arg QueryHistoryParams) ([]QueryHistoryRow, error) {
	rows, err := q.db.Query(ctx, queryHistory, arg.Principal, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryHistoryRow{}
	for rows.Next() {
		var i QueryHistoryRow
		if err := rows.Scan(&i.Sql, &i.DatasourceID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLocale = `-- name: SetLocale :exec
UPDATE app_user SET locale = $1 WHERE principal = $2
`

type SetLocaleParams struct {
	Locale    *string
	Principal string
}

func (q *Queries) SetLocale(ctx context.Context, arg SetLocaleParams) error {
	_, err := q.db.Exec(ctx, setLocale, arg.Locale, arg.Principal)
	return err
}
