// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"
	"time"
)

const addGroupMember = `-- name: AddGroupMember :execrows
INSERT INTO group_member (group_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addGroupRole = `-- name: AddGroupRole :execrows
INSERT INTO group_role (group_id, role_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddGroupRoleParams struct {
	GroupID int64
	RoleID  int64
}

func (q *Queries) AddGroupRole(ctx context.Context, arg AddGroupRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, addGroupRole, arg.GroupID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO app_group (name, description) VALUES ($1, $2) RETURNING id
`

type CreateGroupParams struct {
	Name        string
	Description *string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.Description)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO app_user (principal, display_name, email, active) VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateUserParams struct {
	Principal   string
	DisplayName *string
	Email       *string
	Active      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Principal,
		arg.DisplayName,
		arg.Email,
		arg.Active,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deactivateDaemonSessions = `-- name: DeactivateDaemonSessions :exec
UPDATE principal_session SET liveness_status = 'INACTIVE', absolute_expires_at = now()
WHERE principal = $1 AND kind = 'DAEMON' AND absolute_expires_at > now()
`

func (q *Queries) DeactivateDaemonSessions(ctx context.Context, principal string) error {
	_, err := q.db.Exec(ctx, deactivateDaemonSessions, principal)
	return err
}

const deactivateGrants = `-- name: DeactivateGrants :exec
UPDATE access_grant SET revoked_at = now() WHERE principal = $1 AND revoked_at IS NULL
`

func (q *Queries) DeactivateGrants(ctx context.Context, principal string) error {
	_, err := q.db.Exec(ctx, deactivateGrants, principal)
	return err
}

const deactivateTokens = `-- name: DeactivateTokens :exec
UPDATE proxy_token SET revoked_at = now() WHERE principal = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) DeactivateTokens(ctx context.Context, principal string) error {
	_, err := q.db.Exec(ctx, deactivateTokens, principal)
	return err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE app_user SET active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const deactivateWebSessions = `-- name: DeactivateWebSessions :execrows
UPDATE principal_session SET ended_at = now(), ended_reason = 'DEACTIVATED',
liveness_status = 'INACTIVE' WHERE principal = $1 AND kind = 'WEB' AND ended_at IS NULL
`

func (q *Queries) DeactivateWebSessions(ctx context.Context, principal string) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateWebSessions, principal)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEditorRequests = `-- name: DeleteEditorRequests :exec
DELETE FROM access_request WHERE creator_kind = 'EDITOR' AND principal = $1
`

func (q *Queries) DeleteEditorRequests(ctx context.Context, principal string) error {
	_, err := q.db.Exec(ctx, deleteEditorRequests, principal)
	return err
}

const deleteGroup = `-- name: DeleteGroup :execrows
UPDATE app_group SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePrincipalRoles = `-- name: DeletePrincipalRoles :exec
DELETE FROM principal_role WHERE principal = $1
`

func (q *Queries) DeletePrincipalRoles(ctx context.Context, principal string) error {
	_, err := q.db.Exec(ctx, deletePrincipalRoles, principal)
	return err
}

const deleteTombstone = `-- name: DeleteTombstone :exec
DELETE FROM app_user WHERE principal = $1 AND source = 'SCIM' AND external_id IS NULL
AND NOT active AND ($2::bigint IS NULL OR id <> $2)
`

type DeleteTombstoneParams struct {
	Principal string
	Exclude   *int64
}

func (q *Queries) DeleteTombstone(ctx context.Context, arg DeleteTombstoneParams) error {
	_, err := q.db.Exec(ctx, deleteTombstone, arg.Principal, arg.Exclude)
	return err
}

const group = `-- name: Group :one
SELECT id, name, description, source, external_id FROM app_group WHERE id = $1 AND deleted_at IS NULL
`

type GroupRow struct {
	ID          int64
	Name        string
	Description *string
	Source      string
	ExternalID  *string
}

func (q *Queries) Group(ctx context.Context, id int64) (GroupRow, error) {
	row := q.db.QueryRow(ctx, group, id)
	var i GroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Source,
		&i.ExternalID,
	)
	return i, err
}

const groupMemberCount = `-- name: GroupMemberCount :one
SELECT count(*) FROM group_member WHERE group_id = $1
`

func (q *Queries) GroupMemberCount(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRow(ctx, groupMemberCount, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const groupMemberCounts = `-- name: GroupMemberCounts :many
SELECT group_id, count(*) FROM group_member GROUP BY group_id
`

type GroupMemberCountsRow struct {
	GroupID int64
	Count   int64
}

func (q *Queries) GroupMemberCounts(ctx context.Context) ([]GroupMemberCountsRow, error) {
	rows, err := q.db.Query(ctx, groupMemberCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupMemberCountsRow{}
	for rows.Next() {
		var i GroupMemberCountsRow
		if err := rows.Scan(&i.GroupID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupMembers = `-- name: GroupMembers :many
SELECT u.id, u.principal, u.display_name FROM group_member gm JOIN app_user u ON u.id = gm.user_id
WHERE gm.group_id = $1 ORDER BY u.principal
`

type GroupMembersRow struct {
	ID          int64
	Principal   string
	DisplayName *string
}

func (q *Queries) GroupMembers(ctx context.Context, groupID int64) ([]GroupMembersRow, error) {
	rows, err := q.db.Query(ctx, groupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupMembersRow{}
	for rows.Next() {
		var i GroupMembersRow
		if err := rows.Scan(&i.ID, &i.Principal, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groups = `-- name: Groups :many
SELECT id, name, description, source, external_id FROM app_group WHERE deleted_at IS NULL ORDER BY name
`

type GroupsRow struct {
	ID          int64
	Name        string
	Description *string
	Source      string
	ExternalID  *string
}

func (q *Queries) Groups(ctx context.Context) ([]GroupsRow, error) {
	rows, err := q.db.Query(ctx, groups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupsRow{}
	for rows.Next() {
		var i GroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Source,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupsOfUser = `-- name: GroupsOfUser :many
SELECT gm.user_id, g.id, g.name FROM group_member gm
JOIN app_group g ON g.id = gm.group_id AND g.deleted_at IS NULL WHERE gm.user_id = $1 ORDER BY g.name
`

type GroupsOfUserRow struct {
	UserID int64
	ID     int64
	Name   string
}

func (q *Queries) GroupsOfUser(ctx context.Context, userID int64) ([]GroupsOfUserRow, error) {
	rows, err := q.db.Query(ctx, groupsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupsOfUserRow{}
	for rows.Next() {
		var i GroupsOfUserRow
		if err := rows.Scan(&i.UserID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupsOfUsers = `-- name: GroupsOfUsers :many
SELECT gm.user_id, g.id, g.name FROM group_member gm
JOIN app_group g ON g.id = gm.group_id AND g.deleted_at IS NULL ORDER BY g.name
`

type GroupsOfUsersRow struct {
	UserID int64
	ID     int64
	Name   string
}

func (q *Queries) GroupsOfUsers(ctx context.Context) ([]GroupsOfUsersRow, error) {
	rows, err := q.db.Query(ctx, groupsOfUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupsOfUsersRow{}
	for rows.Next() {
		var i GroupsOfUsersRow
		if err := rows.Scan(&i.UserID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isTombstone = `-- name: IsTombstone :one
SELECT EXISTS (SELECT 1 FROM app_user WHERE principal = $1 AND source = 'SCIM'
AND external_id IS NULL AND NOT active)
`

func (q *Queries) IsTombstone(ctx context.Context, principal string) (bool, error) {
	row := q.db.QueryRow(ctx, isTombstone, principal)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const liveRoleName = `-- name: LiveRoleName :one
SELECT name FROM app_role WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) LiveRoleName(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, liveRoleName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const lockGroup = `-- name: LockGroup :one
SELECT source, name FROM app_group WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

type LockGroupRow struct {
	Source string
	Name   string
}

func (q *Queries) LockGroup(ctx context.Context, id int64) (LockGroupRow, error) {
	row := q.db.QueryRow(ctx, lockGroup, id)
	var i LockGroupRow
	err := row.Scan(&i.Source, &i.Name)
	return i, err
}

const lockPrincipal = `-- name: LockPrincipal :exec
SELECT pg_advisory_xact_lock(hashtext($1))
`

func (q *Queries) LockPrincipal(ctx context.Context, principal string) error {
	_, err := q.db.Exec(ctx, lockPrincipal, principal)
	return err
}

const principalOfUser = `-- name: PrincipalOfUser :one
SELECT principal FROM app_user WHERE id = $1
`

func (q *Queries) PrincipalOfUser(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, principalOfUser, id)
	var principal string
	err := row.Scan(&principal)
	return principal, err
}

const removeGroupMember = `-- name: RemoveGroupMember :execrows
DELETE FROM group_member WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeGroupRole = `-- name: RemoveGroupRole :execrows
DELETE FROM group_role WHERE group_id = $1 AND role_id = $2
`

type RemoveGroupRoleParams struct {
	GroupID int64
	RoleID  int64
}

func (q *Queries) RemoveGroupRole(ctx context.Context, arg RemoveGroupRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGroupRole, arg.GroupID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const roleRefsOfGroup = `-- name: RoleRefsOfGroup :many
SELECT gr.group_id, r.id, r.name FROM group_role gr
JOIN app_role r ON r.id = gr.role_id AND r.deleted_at IS NULL WHERE gr.group_id = $1 ORDER BY r.name
`

type RoleRefsOfGroupRow struct {
	GroupID int64
	ID      int64
	Name    string
}

func (q *Queries) RoleRefsOfGroup(ctx context.Context, groupID int64) ([]RoleRefsOfGroupRow, error) {
	rows, err := q.db.Query(ctx, roleRefsOfGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleRefsOfGroupRow{}
	for rows.Next() {
		var i RoleRefsOfGroupRow
		if err := rows.Scan(&i.GroupID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleRefsOfGroups = `-- name: RoleRefsOfGroups :many
SELECT gr.group_id, r.id, r.name FROM group_role gr
JOIN app_role r ON r.id = gr.role_id AND r.deleted_at IS NULL ORDER BY r.name
`

type RoleRefsOfGroupsRow struct {
	GroupID int64
	ID      int64
	Name    string
}

func (q *Queries) RoleRefsOfGroups(ctx context.Context) ([]RoleRefsOfGroupsRow, error) {
	rows, err := q.db.Query(ctx, roleRefsOfGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleRefsOfGroupsRow{}
	for rows.Next() {
		var i RoleRefsOfGroupsRow
		if err := rows.Scan(&i.GroupID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rolesOfGroup = `-- name: RolesOfGroup :many
SELECT r.id, r.name FROM group_role gr JOIN app_role r ON r.id = gr.role_id AND r.deleted_at IS NULL
WHERE gr.group_id = $1 ORDER BY r.name
`

type RolesOfGroupRow struct {
	ID   int64
	Name string
}

func (q *Queries) RolesOfGroup(ctx context.Context, groupID int64) ([]RolesOfGroupRow, error) {
	rows, err := q.db.Query(ctx, rolesOfGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolesOfGroupRow{}
	for rows.Next() {
		var i RolesOfGroupRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tombstoneUser = `-- name: TombstoneUser :exec
INSERT INTO app_user (principal, source, active) VALUES ($1, 'SCIM', FALSE)
ON CONFLICT (principal) DO UPDATE SET active = FALSE
`

func (q *Queries) TombstoneUser(ctx context.Context, principal string) error {
	_, err := q.db.Exec(ctx, tombstoneUser, principal)
	return err
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE app_group SET name = $1, description = $2 WHERE id = $3 AND deleted_at IS NULL
`

type UpdateGroupParams struct {
	Name        string
	Description *string
	ID          int64
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.Exec(ctx, updateGroup, arg.Name, arg.Description, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE app_user SET principal = $1, display_name = $2, email = $3, active = $4 WHERE id = $5
`

type UpdateUserParams struct {
	Principal   string
	DisplayName *string
	Email       *string
	Active      bool
	ID          int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Principal,
		arg.DisplayName,
		arg.Email,
		arg.Active,
		arg.ID,
	)
	return err
}

const user = `-- name: User :one
SELECT id, principal, display_name, email, source, external_id, active, created_at FROM app_user WHERE id = $1
`

type UserRow struct {
	ID          int64
	Principal   string
	DisplayName *string
	Email       *string
	Source      string
	ExternalID  *string
	Active      bool
	CreatedAt   time.Time
}

func (q *Queries) User(ctx context.Context, id int64) (UserRow, error) {
	row := q.db.QueryRow(ctx, user, id)
	var i UserRow
	err := row.Scan(
		&i.ID,
		&i.Principal,
		&i.DisplayName,
		&i.Email,
		&i.Source,
		&i.ExternalID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const users = `-- name: Users :many
SELECT id, principal, display_name, email, source, external_id, active, created_at FROM app_user ORDER BY principal
`

type UsersRow struct {
	ID          int64
	Principal   string
	DisplayName *string
	Email       *string
	Source      string
	ExternalID  *string
	Active      bool
	CreatedAt   time.Time
}

func (q *Queries) Users(ctx context.Context) ([]UsersRow, error) {
	rows, err := q.db.Query(ctx, users)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersRow{}
	for rows.Next() {
		var i UsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Principal,
			&i.DisplayName,
			&i.Email,
			&i.Source,
			&i.ExternalID,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
