// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: liveness.sql

package db

import (
	"context"
)

const closeDaemonRenewal = `-- name: CloseDaemonRenewal :execrows
UPDATE principal_session SET liveness_status = 'INACTIVE', absolute_expires_at = now()
WHERE id = $1 AND kind = 'DAEMON' AND absolute_expires_at > now()
`

func (q *Queries) CloseDaemonRenewal(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, closeDaemonRenewal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endGroupRevokedSessions = `-- name: EndGroupRevokedSessions :execrows
UPDATE principal_session SET ended_at = now(), ended_reason = 'GROUP_REVOKED', liveness_status = 'INACTIVE'
WHERE principal = $1 AND kind = 'WEB' AND ended_at IS NULL
`

func (q *Queries) EndGroupRevokedSessions(ctx context.Context, principal string) (int64, error) {
	result, err := q.db.Exec(ctx, endGroupRevokedSessions, principal)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markIdpChecked = `-- name: MarkIdpChecked :exec
UPDATE principal_session SET last_idp_check_at = now(),
liveness_status = CASE WHEN ended_at IS NULL THEN 'ACTIVE' ELSE liveness_status END WHERE id = $1
`

func (q *Queries) MarkIdpChecked(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markIdpChecked, id)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :exec
UPDATE principal_session SET refresh_token_enc = $1 WHERE id = $2
`

type RotateRefreshTokenParams struct {
	RefreshTokenEnc []byte
	ID              int64
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, rotateRefreshToken, arg.RefreshTokenEnc, arg.ID)
	return err
}

const staleSessions = `-- name: StaleSessions :many
SELECT id, kind, principal, refresh_token_enc FROM principal_session
WHERE (last_idp_check_at IS NULL OR last_idp_check_at < now() - make_interval(secs => $1))
  AND ((kind = 'DAEMON' AND absolute_expires_at > now())
    OR (kind = 'WEB' AND ended_at IS NULL AND absolute_expires_at > now() AND idle_expires_at > now()))
`

type StaleSessionsRow struct {
	ID              int64
	Kind            string
	Principal       string
	RefreshTokenEnc []byte
}

func (q *Queries) StaleSessions(ctx context.Context, secs float64) ([]StaleSessionsRow, error) {
	rows, err := q.db.Query(ctx, staleSessions, secs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaleSessionsRow{}
	for rows.Next() {
		var i StaleSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Principal,
			&i.RefreshTokenEnc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
