// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type AuditEvent struct {
	ID                 int64
	Ts                 time.Time
	Kind               string
	Principal          string
	Roles              []string
	Datasource         string
	ClientAddr         *string
	Statement          string
	Decision           string
	FailedStage        *string
	MaskedColumns      []string
	PiiTouched         []string
	LatencyMs          int64
	Detail             *string
	EffectiveNamespace []string
	Channel            *string
	ContextTags        []string
	Action             *string
	Resource           *string
	Outcome            *string
	RowsReturned       *int64
	BytesReturned      *int64
	DecisionID         *int64
	ChainVersion       *int32
	PrevHash           []byte
	RowHash            []byte
}
