// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package db

import (
	"context"
	"time"
)

const assignRole = `-- name: AssignRole :one
INSERT INTO principal_role (principal, role_id) VALUES ($1, $2)
ON CONFLICT (principal, role_id) DO UPDATE SET principal = EXCLUDED.principal RETURNING id
`

type AssignRoleParams struct {
	Principal string
	RoleID    int64
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, assignRole, arg.Principal, arg.RoleID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMaskFn = `-- name: CreateMaskFn :one
INSERT INTO mask_fn (name, kind) VALUES ($1, $2) RETURNING id, name, kind
`

type CreateMaskFnParams struct {
	Name string
	Kind string
}

type CreateMaskFnRow struct {
	ID   int64
	Name string
	Kind string
}

func (q *Queries) CreateMaskFn(ctx context.Context, arg CreateMaskFnParams) (CreateMaskFnRow, error) {
	row := q.db.QueryRow(ctx, createMaskFn, arg.Name, arg.Kind)
	var i CreateMaskFnRow
	err := row.Scan(&i.ID, &i.Name, &i.Kind)
	return i, err
}

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policy (name, cedar_src, enabled, updated_by, origin) VALUES ($1, $2, $3, $4, 'USER') RETURNING id
`

type CreatePolicyParams struct {
	Name      string
	CedarSrc  string
	Enabled   bool
	UpdatedBy *string
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPolicy,
		arg.Name,
		arg.CedarSrc,
		arg.Enabled,
		arg.UpdatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO app_role (name, description) VALUES ($1, $2) RETURNING id, name, description
`

type CreateRoleParams struct {
	Name        string
	Description *string
}

type CreateRoleRow struct {
	ID          int64
	Name        string
	Description *string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (CreateRoleRow, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description)
	var i CreateRoleRow
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const deleteMaskFn = `-- name: DeleteMaskFn :execrows
UPDATE mask_fn SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteMaskFn(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMaskFn, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePolicy = `-- name: DeletePolicy :execrows
UPDATE policy SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeletePolicy(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePolicy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRole = `-- name: DeleteRole :execrows
UPDATE app_role SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteRole(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isSystemRole = `-- name: IsSystemRole :one
SELECT EXISTS(SELECT 1 FROM group_role gr JOIN app_group g ON g.id = gr.group_id
WHERE gr.role_id = $1 AND g.source = 'SYSTEM')
`

func (q *Queries) IsSystemRole(ctx context.Context, roleID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isSystemRole, roleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockPolicy = `-- name: LockPolicy :one
SELECT id, origin, system_key, name, cedar_src, enabled, updated_by, updated_at FROM policy WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

type LockPolicyRow struct {
	ID        int64
	Origin    string
	SystemKey *string
	Name      string
	CedarSrc  string
	Enabled   bool
	UpdatedBy *string
	UpdatedAt time.Time
}

func (q *Queries) LockPolicy(ctx context.Context, id int64) (LockPolicyRow, error) {
	row := q.db.QueryRow(ctx, lockPolicy, id)
	var i LockPolicyRow
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.SystemKey,
		&i.Name,
		&i.CedarSrc,
		&i.Enabled,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const maskFn = `-- name: MaskFn :one
SELECT id, name, kind FROM mask_fn WHERE id = $1 AND deleted_at IS NULL
`

type MaskFnRow struct {
	ID   int64
	Name string
	Kind string
}

func (q *Queries) MaskFn(ctx context.Context, id int64) (MaskFnRow, error) {
	row := q.db.QueryRow(ctx, maskFn, id)
	var i MaskFnRow
	err := row.Scan(&i.ID, &i.Name, &i.Kind)
	return i, err
}

const maskFns = `-- name: MaskFns :many
SELECT id, name, kind FROM mask_fn WHERE deleted_at IS NULL ORDER BY name
`

type MaskFnsRow struct {
	ID   int64
	Name string
	Kind string
}

func (q *Queries) MaskFns(ctx context.Context) ([]MaskFnsRow, error) {
	rows, err := q.db.Query(ctx, maskFns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaskFnsRow
	for rows.Next() {
		var i MaskFnsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const policies = `-- name: Policies :many
SELECT id, origin, system_key, name, cedar_src, enabled, updated_by, updated_at
FROM policy WHERE deleted_at IS NULL ORDER BY id
`

type PoliciesRow struct {
	ID        int64
	Origin    string
	SystemKey *string
	Name      string
	CedarSrc  string
	Enabled   bool
	UpdatedBy *string
	UpdatedAt time.Time
}

func (q *Queries) Policies(ctx context.Context) ([]PoliciesRow, error) {
	rows, err := q.db.Query(ctx, policies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoliciesRow
	for rows.Next() {
		var i PoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Origin,
			&i.SystemKey,
			&i.Name,
			&i.CedarSrc,
			&i.Enabled,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const policy = `-- name: Policy :one
SELECT id, origin, system_key, name, cedar_src, enabled, updated_by, updated_at FROM policy WHERE id = $1 AND deleted_at IS NULL
`

type PolicyRow struct {
	ID        int64
	Origin    string
	SystemKey *string
	Name      string
	CedarSrc  string
	Enabled   bool
	UpdatedBy *string
	UpdatedAt time.Time
}

func (q *Queries) Policy(ctx context.Context, id int64) (PolicyRow, error) {
	row := q.db.QueryRow(ctx, policy, id)
	var i PolicyRow
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.SystemKey,
		&i.Name,
		&i.CedarSrc,
		&i.Enabled,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const role = `-- name: Role :one
SELECT id, name, description FROM app_role WHERE id = $1 AND deleted_at IS NULL
`

type RoleRow struct {
	ID          int64
	Name        string
	Description *string
}

func (q *Queries) Role(ctx context.Context, id int64) (RoleRow, error) {
	row := q.db.QueryRow(ctx, role, id)
	var i RoleRow
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const roleAssigned = `-- name: RoleAssigned :one
SELECT EXISTS(SELECT 1 FROM principal_role WHERE principal = $1 AND role_id = $2)
`

type RoleAssignedParams struct {
	Principal string
	RoleID    int64
}

func (q *Queries) RoleAssigned(ctx context.Context, arg RoleAssignedParams) (bool, error) {
	row := q.db.QueryRow(ctx, roleAssigned, arg.Principal, arg.RoleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const roleAssignment = `-- name: RoleAssignment :one
SELECT pr.id, pr.principal, pr.role_id, r.name AS role_name
FROM principal_role pr JOIN app_role r ON r.id = pr.role_id AND r.deleted_at IS NULL WHERE pr.id = $1
`

type RoleAssignmentRow struct {
	ID        int64
	Principal string
	RoleID    int64
	RoleName  string
}

func (q *Queries) RoleAssignment(ctx context.Context, id int64) (RoleAssignmentRow, error) {
	row := q.db.QueryRow(ctx, roleAssignment, id)
	var i RoleAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.Principal,
		&i.RoleID,
		&i.RoleName,
	)
	return i, err
}

const roleAssignments = `-- name: RoleAssignments :many
SELECT pr.id, pr.principal, pr.role_id, r.name AS role_name
FROM principal_role pr JOIN app_role r ON r.id = pr.role_id AND r.deleted_at IS NULL WHERE true
ORDER BY pr.principal, r.name
`

type RoleAssignmentsRow struct {
	ID        int64
	Principal string
	RoleID    int64
	RoleName  string
}

func (q *Queries) RoleAssignments(ctx context.Context) ([]RoleAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, roleAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleAssignmentsRow
	for rows.Next() {
		var i RoleAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Principal,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleAssignmentsOfPrincipal = `-- name: RoleAssignmentsOfPrincipal :many
SELECT pr.id, pr.principal, pr.role_id, r.name AS role_name
FROM principal_role pr JOIN app_role r ON r.id = pr.role_id AND r.deleted_at IS NULL WHERE true AND pr.principal = $1
ORDER BY pr.principal, r.name
`

type RoleAssignmentsOfPrincipalRow struct {
	ID        int64
	Principal string
	RoleID    int64
	RoleName  string
}

func (q *Queries) RoleAssignmentsOfPrincipal(ctx context.Context, principal string) ([]RoleAssignmentsOfPrincipalRow, error) {
	rows, err := q.db.Query(ctx, roleAssignmentsOfPrincipal, principal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleAssignmentsOfPrincipalRow
	for rows.Next() {
		var i RoleAssignmentsOfPrincipalRow
		if err := rows.Scan(
			&i.ID,
			&i.Principal,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleAssignmentsOfPrincipalRole = `-- name: RoleAssignmentsOfPrincipalRole :many
SELECT pr.id, pr.principal, pr.role_id, r.name AS role_name
FROM principal_role pr JOIN app_role r ON r.id = pr.role_id AND r.deleted_at IS NULL WHERE true AND pr.principal = $1 AND pr.role_id = $2
ORDER BY pr.principal, r.name
`

type RoleAssignmentsOfPrincipalRoleParams struct {
	Principal string
	RoleID    int64
}

type RoleAssignmentsOfPrincipalRoleRow struct {
	ID        int64
	Principal string
	RoleID    int64
	RoleName  string
}

func (q *Queries) RoleAssignmentsOfPrincipalRole(ctx context.Context, arg RoleAssignmentsOfPrincipalRoleParams) ([]RoleAssignmentsOfPrincipalRoleRow, error) {
	rows, err := q.db.Query(ctx, roleAssignmentsOfPrincipalRole, arg.Principal, arg.RoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleAssignmentsOfPrincipalRoleRow
	for rows.Next() {
		var i RoleAssignmentsOfPrincipalRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Principal,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleAssignmentsOfRole = `-- name: RoleAssignmentsOfRole :many
SELECT pr.id, pr.principal, pr.role_id, r.name AS role_name
FROM principal_role pr JOIN app_role r ON r.id = pr.role_id AND r.deleted_at IS NULL WHERE true AND pr.role_id = $1
ORDER BY pr.principal, r.name
`

type RoleAssignmentsOfRoleRow struct {
	ID        int64
	Principal string
	RoleID    int64
	RoleName  string
}

func (q *Queries) RoleAssignmentsOfRole(ctx context.Context, roleID int64) ([]RoleAssignmentsOfRoleRow, error) {
	rows, err := q.db.Query(ctx, roleAssignmentsOfRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleAssignmentsOfRoleRow
	for rows.Next() {
		var i RoleAssignmentsOfRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Principal,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roles = `-- name: Roles :many
SELECT id, name, description FROM app_role WHERE deleted_at IS NULL ORDER BY name
`

type RolesRow struct {
	ID          int64
	Name        string
	Description *string
}

func (q *Queries) Roles(ctx context.Context) ([]RolesRow, error) {
	rows, err := q.db.Query(ctx, roles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolesRow
	for rows.Next() {
		var i RolesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPolicyEnabled = `-- name: SetPolicyEnabled :exec
UPDATE policy SET enabled = $1, updated_by = $2, updated_at = now() WHERE id = $3 AND deleted_at IS NULL
`

type SetPolicyEnabledParams struct {
	Enabled   bool
	UpdatedBy *string
	ID        int64
}

func (q *Queries) SetPolicyEnabled(ctx context.Context, arg SetPolicyEnabledParams) error {
	_, err := q.db.Exec(ctx, setPolicyEnabled, arg.Enabled, arg.UpdatedBy, arg.ID)
	return err
}

const unassignRole = `-- name: UnassignRole :execrows
DELETE FROM principal_role WHERE id = $1
`

func (q *Queries) UnassignRole(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, unassignRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMaskFn = `-- name: UpdateMaskFn :exec
UPDATE mask_fn SET name = $1, kind = $2 WHERE id = $3 AND deleted_at IS NULL
`

type UpdateMaskFnParams struct {
	Name string
	Kind string
	ID   int64
}

func (q *Queries) UpdateMaskFn(ctx context.Context, arg UpdateMaskFnParams) error {
	_, err := q.db.Exec(ctx, updateMaskFn, arg.Name, arg.Kind, arg.ID)
	return err
}

const updatePolicy = `-- name: UpdatePolicy :exec
UPDATE policy SET name = $1, cedar_src = $2, enabled = $3, updated_by = $4, updated_at = now() WHERE id = $5 AND deleted_at IS NULL
`

type UpdatePolicyParams struct {
	Name      string
	CedarSrc  string
	Enabled   bool
	UpdatedBy *string
	ID        int64
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) error {
	_, err := q.db.Exec(ctx, updatePolicy,
		arg.Name,
		arg.CedarSrc,
		arg.Enabled,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE app_role SET name = $1, description = $2 WHERE id = $3 AND deleted_at IS NULL
`

type UpdateRoleParams struct {
	Name        string
	Description *string
	ID          int64
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole, arg.Name, arg.Description, arg.ID)
	return err
}
