// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package db

import (
	"context"
	"time"
)

const maskFns = `-- name: MaskFns :many
SELECT id, name, kind FROM mask_fn WHERE deleted_at IS NULL ORDER BY name
`

type MaskFnsRow struct {
	ID   int64
	Name string
	Kind string
}

func (q *Queries) MaskFns(ctx context.Context) ([]MaskFnsRow, error) {
	rows, err := q.db.Query(ctx, maskFns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaskFnsRow
	for rows.Next() {
		var i MaskFnsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const policies = `-- name: Policies :many
SELECT id, origin, system_key, name, cedar_src, enabled, updated_by, updated_at
FROM policy WHERE deleted_at IS NULL ORDER BY id
`

type PoliciesRow struct {
	ID        int64
	Origin    string
	SystemKey *string
	Name      string
	CedarSrc  string
	Enabled   bool
	UpdatedBy *string
	UpdatedAt time.Time
}

func (q *Queries) Policies(ctx context.Context) ([]PoliciesRow, error) {
	rows, err := q.db.Query(ctx, policies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoliciesRow
	for rows.Next() {
		var i PoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Origin,
			&i.SystemKey,
			&i.Name,
			&i.CedarSrc,
			&i.Enabled,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleAssignments = `-- name: RoleAssignments :many
SELECT pr.id, pr.principal, pr.role_id, r.name AS role_name
FROM principal_role pr JOIN app_role r ON r.id = pr.role_id AND r.deleted_at IS NULL WHERE true
ORDER BY pr.principal, r.name
`

type RoleAssignmentsRow struct {
	ID        int64
	Principal string
	RoleID    int64
	RoleName  string
}

func (q *Queries) RoleAssignments(ctx context.Context) ([]RoleAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, roleAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleAssignmentsRow
	for rows.Next() {
		var i RoleAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Principal,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleAssignmentsOfPrincipal = `-- name: RoleAssignmentsOfPrincipal :many
SELECT pr.id, pr.principal, pr.role_id, r.name AS role_name
FROM principal_role pr JOIN app_role r ON r.id = pr.role_id AND r.deleted_at IS NULL WHERE true AND pr.principal = $1
ORDER BY pr.principal, r.name
`

type RoleAssignmentsOfPrincipalRow struct {
	ID        int64
	Principal string
	RoleID    int64
	RoleName  string
}

func (q *Queries) RoleAssignmentsOfPrincipal(ctx context.Context, principal string) ([]RoleAssignmentsOfPrincipalRow, error) {
	rows, err := q.db.Query(ctx, roleAssignmentsOfPrincipal, principal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleAssignmentsOfPrincipalRow
	for rows.Next() {
		var i RoleAssignmentsOfPrincipalRow
		if err := rows.Scan(
			&i.ID,
			&i.Principal,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleAssignmentsOfPrincipalRole = `-- name: RoleAssignmentsOfPrincipalRole :many
SELECT pr.id, pr.principal, pr.role_id, r.name AS role_name
FROM principal_role pr JOIN app_role r ON r.id = pr.role_id AND r.deleted_at IS NULL WHERE true AND pr.principal = $1 AND pr.role_id = $2
ORDER BY pr.principal, r.name
`

type RoleAssignmentsOfPrincipalRoleParams struct {
	Principal string
	RoleID    int64
}

type RoleAssignmentsOfPrincipalRoleRow struct {
	ID        int64
	Principal string
	RoleID    int64
	RoleName  string
}

func (q *Queries) RoleAssignmentsOfPrincipalRole(ctx context.Context, arg RoleAssignmentsOfPrincipalRoleParams) ([]RoleAssignmentsOfPrincipalRoleRow, error) {
	rows, err := q.db.Query(ctx, roleAssignmentsOfPrincipalRole, arg.Principal, arg.RoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleAssignmentsOfPrincipalRoleRow
	for rows.Next() {
		var i RoleAssignmentsOfPrincipalRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Principal,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleAssignmentsOfRole = `-- name: RoleAssignmentsOfRole :many
SELECT pr.id, pr.principal, pr.role_id, r.name AS role_name
FROM principal_role pr JOIN app_role r ON r.id = pr.role_id AND r.deleted_at IS NULL WHERE true AND pr.role_id = $1
ORDER BY pr.principal, r.name
`

type RoleAssignmentsOfRoleRow struct {
	ID        int64
	Principal string
	RoleID    int64
	RoleName  string
}

func (q *Queries) RoleAssignmentsOfRole(ctx context.Context, roleID int64) ([]RoleAssignmentsOfRoleRow, error) {
	rows, err := q.db.Query(ctx, roleAssignmentsOfRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleAssignmentsOfRoleRow
	for rows.Next() {
		var i RoleAssignmentsOfRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Principal,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roles = `-- name: Roles :many
SELECT id, name, description FROM app_role WHERE deleted_at IS NULL ORDER BY name
`

type RolesRow struct {
	ID          int64
	Name        string
	Description *string
}

func (q *Queries) Roles(ctx context.Context) ([]RolesRow, error) {
	rows, err := q.db.Query(ctx, roles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolesRow
	for rows.Next() {
		var i RolesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
