// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provision.sql

package db

import (
	"context"
)

const groupIDsOfUser = `-- name: GroupIDsOfUser :many
SELECT group_id FROM group_member WHERE user_id = $1
`

func (q *Queries) GroupIDsOfUser(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, groupIDsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var group_id int64
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const provisionGroup = `-- name: ProvisionGroup :one
INSERT INTO app_group (name, source) VALUES ($1, 'OIDC')
ON CONFLICT (name) WHERE deleted_at IS NULL DO UPDATE SET name = EXCLUDED.name RETURNING id
`

func (q *Queries) ProvisionGroup(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, provisionGroup, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const provisionUser = `-- name: ProvisionUser :exec
INSERT INTO app_user (principal, email, source, active) VALUES ($1, $2, 'OIDC', TRUE)
ON CONFLICT (principal) DO UPDATE SET email = COALESCE(EXCLUDED.email, app_user.email), source = EXCLUDED.source
WHERE app_user.source <> 'SCIM'
`

type ProvisionUserParams struct {
	Principal string
	Email     *string
}

func (q *Queries) ProvisionUser(ctx context.Context, arg ProvisionUserParams) error {
	_, err := q.db.Exec(ctx, provisionUser, arg.Principal, arg.Email)
	return err
}

const userIDByPrincipal = `-- name: UserIDByPrincipal :one
SELECT id FROM app_user WHERE principal = $1
`

func (q *Queries) UserIDByPrincipal(ctx context.Context, principal string) (int64, error) {
	row := q.db.QueryRow(ctx, userIDByPrincipal, principal)
	var id int64
	err := row.Scan(&id)
	return id, err
}
