// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"
	"time"
)

const liveWebSession = `-- name: LiveWebSession :one
SELECT id, principal, created_at, absolute_expires_at, idle_expires_at, device_id,
       coalesce(debug_requester_ip, '')::text AS debug_requester_ip, clock_timestamp()::timestamptz AS db_now
FROM principal_session
WHERE session_key = $1 AND kind = 'WEB' AND ended_at IS NULL
  AND absolute_expires_at > clock_timestamp()
  AND idle_expires_at > clock_timestamp()
`

type LiveWebSessionRow struct {
	ID                int64
	Principal         string
	CreatedAt         time.Time
	AbsoluteExpiresAt time.Time
	IdleExpiresAt     *time.Time
	DeviceID          *string
	DebugRequesterIp  string
	DbNow             time.Time
}

func (q *Queries) LiveWebSession(ctx context.Context, sessionKey *string) (LiveWebSessionRow, error) {
	row := q.db.QueryRow(ctx, liveWebSession, sessionKey)
	var i LiveWebSessionRow
	err := row.Scan(
		&i.ID,
		&i.Principal,
		&i.CreatedAt,
		&i.AbsoluteExpiresAt,
		&i.IdleExpiresAt,
		&i.DeviceID,
		&i.DebugRequesterIp,
		&i.DbNow,
	)
	return i, err
}

const wirePrincipal = `-- name: WirePrincipal :one
SELECT t.principal FROM proxy_token t
WHERE t.token_hash = $1 AND t.kind IN ('SESSION', 'USER') AND t.revoked_at IS NULL
  AND t.retired_at IS NULL AND t.expires_at > now()
  AND NOT EXISTS (SELECT 1 FROM app_user u WHERE u.principal = t.principal AND NOT u.active)
`

func (q *Queries) WirePrincipal(ctx context.Context, tokenHash string) (string, error) {
	row := q.db.QueryRow(ctx, wirePrincipal, tokenHash)
	var principal string
	err := row.Scan(&principal)
	return principal, err
}
