// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"
	"time"
)

const liveWebSession = `-- name: LiveWebSession :one
SELECT id, principal, created_at, absolute_expires_at, idle_expires_at, device_id,
       coalesce(debug_requester_ip, '')::text AS debug_requester_ip, clock_timestamp()::timestamptz AS db_now
FROM principal_session
WHERE session_key = $1 AND kind = 'WEB' AND ended_at IS NULL
  AND absolute_expires_at > clock_timestamp()
  AND idle_expires_at > clock_timestamp()
`

type LiveWebSessionRow struct {
	ID                int64
	Principal         string
	CreatedAt         time.Time
	AbsoluteExpiresAt time.Time
	IdleExpiresAt     *time.Time
	DeviceID          *string
	DebugRequesterIp  string
	DbNow             time.Time
}

func (q *Queries) LiveWebSession(ctx context.Context, sessionKey *string) (LiveWebSessionRow, error) {
	row := q.db.QueryRow(ctx, liveWebSession, sessionKey)
	var i LiveWebSessionRow
	err := row.Scan(
		&i.ID,
		&i.Principal,
		&i.CreatedAt,
		&i.AbsoluteExpiresAt,
		&i.IdleExpiresAt,
		&i.DeviceID,
		&i.DebugRequesterIp,
		&i.DbNow,
	)
	return i, err
}
