// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package db

import (
	"context"
	"time"
)

const mintToken = `-- name: MintToken :one
INSERT INTO proxy_token (token_hash, kind, principal, roles, name, expires_at)
VALUES ($1, $2, $3, '[]'::jsonb, $4, now() + ($5::bigint * interval '1 second')) RETURNING id, expires_at
`

type MintTokenParams struct {
	TokenHash string
	Kind      string
	Principal string
	Name      *string
	Ttl       int64
}

type MintTokenRow struct {
	ID        int64
	ExpiresAt time.Time
}

func (q *Queries) MintToken(ctx context.Context, arg MintTokenParams) (MintTokenRow, error) {
	row := q.db.QueryRow(ctx, mintToken,
		arg.TokenHash,
		arg.Kind,
		arg.Principal,
		arg.Name,
		arg.Ttl,
	)
	var i MintTokenRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const revokeWireToken = `-- name: RevokeWireToken :execrows
UPDATE proxy_token SET revoked_at = now() WHERE id = $1 AND principal = $2 AND revoked_at IS NULL
`

type RevokeWireTokenParams struct {
	ID        int64
	Principal string
}

func (q *Queries) RevokeWireToken(ctx context.Context, arg RevokeWireTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeWireToken, arg.ID, arg.Principal)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const wireToken = `-- name: WireToken :one
SELECT id, kind, principal, name, created_at, expires_at, revoked_at, last_used_at FROM proxy_token WHERE id = $1
`

type WireTokenRow struct {
	ID         int64
	Kind       string
	Principal  string
	Name       *string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	LastUsedAt *time.Time
}

func (q *Queries) WireToken(ctx context.Context, id int64) (WireTokenRow, error) {
	row := q.db.QueryRow(ctx, wireToken, id)
	var i WireTokenRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Principal,
		&i.Name,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const wireTokens = `-- name: WireTokens :many
SELECT id, kind, principal, name, created_at, expires_at, revoked_at, last_used_at FROM proxy_token
WHERE principal = $1 AND kind IN ('SESSION', 'USER') ORDER BY created_at DESC
`

type WireTokensRow struct {
	ID         int64
	Kind       string
	Principal  string
	Name       *string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	LastUsedAt *time.Time
}

func (q *Queries) WireTokens(ctx context.Context, principal string) ([]WireTokensRow, error) {
	rows, err := q.db.Query(ctx, wireTokens, principal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WireTokensRow{}
	for rows.Next() {
		var i WireTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Principal,
			&i.Name,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
