package mysqlproxy

import (
	"context"
	"crypto/tls"
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/ridi-oss/proxy-monster/goproxy/internal/dbtest"
	"github.com/ridi-oss/proxy-monster/goproxy/spi"
	"github.com/ridi-oss/proxy-monster/goproxy/targettls"
)

func tlsOnlyTarget(t *testing.T, config *tls.Config) spi.TargetDb {
	t.Helper()
	db := dbtest.MySQLTLS(t)
	return spi.TargetDb{Host: db.Host, Port: db.Port, Db: db.DB, User: db.User, Password: db.Password, TLS: config}
}

func TestTargetDbTLSVerifyFull(t *testing.T) {
	target := tlsOnlyTarget(t, nil)
	config, err := targettls.Config(targettls.VerifyFull, dbtest.TLSCAFile(), target.Host)
	if err != nil {
		t.Fatal(err)
	}
	target.TLS = config
	conn, _, err := dialTargetDbAuthID(context.Background(), target, true)
	if err != nil {
		t.Fatalf("verify-full dial: %v", err)
	}
	defer conn.Close()
	if _, ok := conn.(*tls.Conn); !ok {
		t.Fatalf("target conn = %T, want *tls.Conn", conn)
	}
}

func TestTargetDbTLSPlaintextIsRefused(t *testing.T) {
	_, _, err := dialTargetDbAuthID(context.Background(), tlsOnlyTarget(t, nil), true)
	if err == nil || !strings.Contains(err.Error(), "secure transport") {
		t.Fatalf("plaintext dial to a require_secure_transport target = %v, want a secure-transport rejection", err)
	}
}

func TestTargetDbTLSRejectsUntrustedCertificate(t *testing.T) {
	target := tlsOnlyTarget(t, nil)
	config, err := targettls.Config(targettls.VerifyFull, "rds", target.Host)
	if err != nil {
		t.Fatal(err)
	}
	target.TLS = config
	_, _, err = dialTargetDbAuthID(context.Background(), target, true)
	if err == nil || !strings.Contains(err.Error(), "certificate") {
		t.Fatalf("verify-full against the RDS bundle = %v, want a certificate error", err)
	}
}

// A fresh user misses the fast-auth cache, so the server demands full auth, sent in cleartext inside TLS.
func TestTargetDbTLSCachingSHA2FullAuth(t *testing.T) {
	db := dbtest.MySQLTLS(t)
	seed := dbtest.Open(t, "mysql", fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?tls=skip-verify", db.User, db.Password, db.Host, db.Port, db.DB))
	user := fmt.Sprintf("it_tls_csha2_%d", time.Now().UnixNano())
	const password = "tls-full-auth-pw"
	if _, err := seed.Exec("CREATE USER '" + user + "'@'%' IDENTIFIED WITH caching_sha2_password BY '" + password + "'"); err != nil {
		t.Fatalf("create caching_sha2 user: %v", err)
	}
	if _, err := seed.Exec("GRANT SELECT ON " + db.DB + ".* TO '" + user + "'@'%'"); err != nil {
		t.Fatalf("grant caching_sha2 user: %v", err)
	}
	t.Cleanup(func() { _, _ = seed.Exec("DROP USER IF EXISTS '" + user + "'@'%'") })

	var cleartext, publicKey int
	testHookCachingSHA2FullAuth = func(viaPublicKey bool) {
		if viaPublicKey {
			publicKey++
		} else {
			cleartext++
		}
	}
	t.Cleanup(func() { testHookCachingSHA2FullAuth = nil })

	target := spi.TargetDb{Host: db.Host, Port: db.Port, Db: db.DB, User: user, Password: password, TLS: dbtest.VerifyFullTLS(t, db.Host)}
	conn, _, err := dialTargetDbAuthID(context.Background(), target, true)
	if err != nil {
		t.Fatalf("caching_sha2 full auth over TLS: %v", err)
	}
	conn.Close()
	if cleartext != 1 || publicKey != 0 {
		t.Fatalf("full auth ran cleartext=%d publicKey=%d, want the TLS cleartext branch once", cleartext, publicKey)
	}
}

func TestTargetDbTLSRequire(t *testing.T) {
	target := tlsOnlyTarget(t, nil)
	config, err := targettls.Config(targettls.Require, "", target.Host)
	if err != nil {
		t.Fatal(err)
	}
	target.TLS = config
	conn, _, err := dialTargetDbAuthID(context.Background(), target, true)
	if err != nil {
		t.Fatalf("require dial: %v", err)
	}
	conn.Close()
}

func TestTargetDbTLSRejectsHostnameMismatch(t *testing.T) {
	target := tlsOnlyTarget(t, nil)
	config, err := targettls.Config(targettls.VerifyFull, dbtest.TLSCAFile(), "not-the-san.example")
	if err != nil {
		t.Fatal(err)
	}
	target.TLS = config
	_, _, err = dialTargetDbAuthID(context.Background(), target, true)
	if err == nil || !strings.Contains(err.Error(), "not-the-san.example") {
		t.Fatalf("verify-full with a mismatched host = %v, want a hostname error", err)
	}
}

// MySQL ships an auto-generated self-signed certificate, which verify-full must refuse.
func TestTargetDbTLSRejectsAutoGeneratedCertificate(t *testing.T) {
	db := dbtest.MySQL(t)
	target := spi.TargetDb{Host: db.Host, Port: db.Port, Db: db.DB, User: db.User, Password: db.Password, TLS: dbtest.VerifyFullTLS(t, db.Host)}
	if _, _, err := dialTargetDbAuthID(context.Background(), target, true); err == nil {
		t.Fatal("verify-full accepted the server's auto-generated certificate")
	}
}

// A Cloud SQL per-instance certificate names no DNS host, so verify-ca must pass on the chain alone.
func TestTargetDbTLSVerifyCAIgnoresHostname(t *testing.T) {
	target := tlsOnlyTarget(t, nil)
	config, err := targettls.Config(targettls.VerifyCA, dbtest.TLSCAFile(), "my-project:my-instance")
	if err != nil {
		t.Fatal(err)
	}
	target.TLS = config
	conn, _, err := dialTargetDbAuthID(context.Background(), target, true)
	if err != nil {
		t.Fatalf("verify-ca dial: %v", err)
	}
	conn.Close()

	if target.TLS, err = targettls.Config(targettls.VerifyCA, dbtest.OtherCAFile(), target.Host); err != nil {
		t.Fatal(err)
	}
	if _, _, err = dialTargetDbAuthID(context.Background(), target, true); err == nil || !strings.Contains(err.Error(), "certificate") {
		t.Fatalf("verify-ca with an unrelated CA = %v, want a certificate error", err)
	}
}
